# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  BuildPlatform: 'any cpu'

steps:
 - task: DotNetCoreInstaller@0
   displayName: 'Install .Net core 2.2 SDK'
   inputs:
    packageType: 'sdk'
    version: '2.2.100'
 
 - script: dotnet build appinsights-releaseannotation/appinsights-releaseannotation.sln --configuration $(buildConfiguration) 
   displayName: 'dotnet build $(buildConfiguration)'

 - task: DotNetCoreCLI@2
   displayName: 'Publish build artifacts'
   inputs:
    command: publish
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    projects: appinsights-releaseannotation/appinsights-releaseannotation/appinsights-releaseannotation.csproj
    publishWebProjects: false
    modifyOutputPath: true
    zipAfterPublish: true
 
 - task: PublishBuildArtifacts@1
